### ISSUE TITLE
revisit scda decoupling

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/osprey#123]
### What is your question?

I think we should apply the same changes to osprey as we did in the follow-up to decoupling at teal.transform https://github.com/insightsengineering/teal.transform/pull/142

Main wishes are
- prepend dataset names with package names as now we are having the same data in multiple packages (`teal.transform::rADAE` and `teal.modules.general::rADAE` for example)
- add a `data-raw/data.R` file to show how the `data/` folder was created
- extend `.RBuildignore` file to omit `data-raw/data.R` while building the package

cc @kartikeyakirar @gogonzo 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by gogonzo** [comment]
> prepend dataset names with package names as now we are having the same data in multiple packages (teal.transform::rADAE and teal.modules.general::rADAE for example)

I disagree. `osprey` is on the top of dependency tree, it doesn't depend on any of teal.* packages.

> - add a data-raw/data.R file to show how the data/ folder was created
> - extend .RBuildignore file to omit data-raw/data.R while building the package

Good point

**Comment by m7pr** [comment]
what about the situation where you load `osprey` and then you load some `teal.*` packages. then the calls to datasets gets clunky as there is a clash in object names being used in multiple packages. the datasets will be used from the last loaded package and can be different
