### ISSUE TITLE
Removing marker on swimlane plot adds gap in graph

### ISSUE THREAD

**Issue by cicdguy** [insightsengineering/osprey#7]
<REDACTED>content/4256/

Is this expected? Desired?

Compare:

![image](https://user-images.githubusercontent.com/12943682/128377098-f17074b4-89ae-41a7-aaa1-89367430c7a0.png)
![image](https://user-images.githubusercontent.com/12943682/128377120-36994945-fccf-47ce-ab2b-3a6d5d088ded.png)

Provenance: 
```
Creator: nikolas-burkoff
```

**Comment by donyunardi** [comment]
Closing for now because there are no complain from user since OP.
