### ISSUE TITLE
Fix `tm_g_patient_profile` examples

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/osprey#97]
When running the roxygen examples for both functions in the file you get errors running:

```
  rADSL <- synthetic_cdisc_data("latest")$adsl
  ADSL <- rADSL %>%
    group_by(USUBJID) %>%
    mutate(
      TRTSDT = as.Date(TRTSDTM),
      max_date = max(as.Date(LSTALVDT), as.Date(DTHDT), na.rm = TRUE),
      max_day = as.numeric(as.Date(max_date) - as.Date(TRTSDT)) + 1
    ) %>%
    select(USUBJID, STUDYID, TRTSDT, max_day) %>%
    filter(USUBJID == rADSL$USUBJID[1])
```

As lots of subjects have no non-missing LSTALVDT and DTHDT values - this could be fixed by adding `-Inf` into the `max` statement but that throws up other errors later on

@kumamiao should I just filter out all subjects which do not have at least one non missing LSTALVDT or DTHDT date? Any thoughts?

**Comment by kumamiao** [comment]
Thanks @nikolas-burkoff ! Not all patients would have death date (DTHDT), but technically they all should have last known alive date (LSTALVDT), so the random data here might not be completely aligned to standards (I noticed also some did not have TRTEDT). But just for the purpose of showing example, we can filter out patients who do not have LSTALVDT, and grab the max of LSTALVDT & DTHDT if both are present. Thanks!
